FROM nginx:1.23.1-alpine as prod-stage
COPY default.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]

#to install vim to nginx server
RUN ["apk", "update"]
RUN ["apk", "add", "vim"]
